# Generated by Django 6.0.5 on 2026-06-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="payment_link",
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату Stripe"),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет"), ("stripe", "Оплата через Stripe")],
                help_text="Способ оплаты: наличные или перевод на счет.",
                max_length=100,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
