# Generated by Django 6.0.5 on 2026-06-30 20:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payments_payment_link_payments_session_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payments",
            options={"ordering": ["-created_at"], "verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
        migrations.RemoveField(
            model_name="payments",
            name="payment_date",
        ),
        migrations.AddField(
            model_name="payments",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Дата и время оплаты"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payments",
            name="status",
            field=models.CharField(
                choices=[("open", "В процессе"), ("complete", "Оплачен"), ("expired", "Просрочен/Отменен")],
                default="open",
                max_length=50,
                verbose_name="Статус платежа",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет"), ("stripe", "Оплата через Stripe")],
                help_text="Способ оплаты: наличные, перевод на счет или онлайн через Stripe.",
                max_length=100,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
