# Generated by Django 6.0.5 on 2026-05-31 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Введите название курса", max_length=150, verbose_name="Курс")),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Подгрузите превью курса",
                        null=True,
                        upload_to="learnings/course_previews/",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Добавьте описание курса", null=True, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Введите название урока", max_length=150, verbose_name="Урок")),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте превью урока",
                        null=True,
                        upload_to="learnings/lesson_previews/",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Добавьте описание урока", null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "link_to_video",
                    models.URLField(
                        blank=True,
                        help_text="Добавьте ссылку на видео урока",
                        max_length=500,
                        null=True,
                        verbose_name="Ссылка на видео урока",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Выберите курс",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="learnings.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
