# Generated by Django 6.0.5 on 2026-06-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learnings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["title"], "verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
    ]
