# Generated by Django 6.0.5 on 2026-06-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learnings", "0005_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=5000, verbose_name="Цена курса"),
        ),
    ]
