# Generated by Django 6.0.5 on 2026-07-01 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learnings", "0006_alter_course_options_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата последнего обновления"),
        ),
    ]
